const state={key:"",overview:null,map:null,config:[],changes:{},monitor:[],monitorTimer:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtBytes=n=>{if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0;while(n>=1024&&i<3){n/=1024;i++}return `${n.toFixed(i>1?1:0)} ${u[i]}`};
const fmtDuration=s=>{if(s<60)return`${s}s`;if(s<3600)return`${Math.floor(s/60)}m`;if(s<86400)return`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`;return`${Math.floor(s/86400)}d ${Math.floor(s%86400/3600)}h`};
async function api(path,options={}){const headers={"X-API-Key":state.key,...options.headers};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});if(!response.ok){let msg=`HTTP ${response.status}`;try{const body=await response.json();msg=body.message||body.error||msg}catch{}throw new Error(msg)}if(response.status===204)return null;return response.json()}
function toast(message,bad=false){const el=$("#toast");el.textContent=message;el.style.borderColor=bad?"#753e3a":"#386858";el.classList.add("show");setTimeout(()=>el.classList.remove("show"),3200)}
async function connect(key,{persist=true}={}){state.key=key;const overview=await api("/v1/admin/overview");if(persist)sessionStorage.setItem("lumenvec.admin.apiKey",key);state.overview=overview;$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");renderOverview(overview);recordMonitorSample(overview);startMonitor();await Promise.all([loadMap(100,$("#overview-map")),loadCluster(),loadConfig()])}
$("#login-form").addEventListener("submit",async e=>{e.preventDefault();$("#login-error").textContent="";try{await connect($("#api-key").value)}catch(err){state.key="";sessionStorage.removeItem("lumenvec.admin.apiKey");$("#login-error").textContent=err.message}});
$("#logout").onclick=()=>{sessionStorage.removeItem("lumenvec.admin.apiKey");state.key="";location.reload()};
$$(".nav-item").forEach(button=>button.onclick=()=>showPage(button.dataset.page));
$$("[data-goto]").forEach(button=>button.onclick=()=>showPage(button.dataset.goto));
function showPage(page){$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));$$(".page").forEach(p=>p.classList.toggle("active",p.id===`page-${page}`));$("#page-title").textContent={overview:"Visão geral",monitor:"Monitor",explorer:"Vector Explorer",cluster:"Cluster",settings:"Configurações"}[page];if(page==="explorer")loadMap(Number($("#sample-limit").value),$("#vector-map"));if(page==="monitor")renderMonitor()}
$("#refresh").onclick=async()=>{try{const data=await api("/v1/admin/overview");renderOverview(data);recordMonitorSample(data);await loadCluster();toast("Dados atualizados")}catch(e){toast(e.message,true)}};
$("#sample-limit").onchange=()=>loadMap(Number($("#sample-limit").value),$("#vector-map"));
function renderOverview(o){state.overview=o;$("#vector-count").textContent=o.vector_count.toLocaleString("pt-BR");$("#memory").textContent=fmtBytes(o.memory.sys_bytes);$("#heap").textContent=`heap ${fmtBytes(o.memory.heap_bytes)}`;$("#ready-nodes").textContent=`${o.cluster.ready_nodes}/${o.cluster.desired_nodes}`;$("#cluster-phase").textContent=o.cluster.phase||o.cluster.provider;$("#uptime").textContent=fmtDuration(o.uptime_seconds);$("#goroutines").textContent=`${o.goroutines} goroutines`;$("#ann-summary").textContent=`${o.stats.ann_segments||0} segmentos · ${o.stats.ann_profile||"exact"}`;$("#side-node").textContent=o.cluster.name||o.cluster.provider;$("#updated").textContent=new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});const rows=[["Perfil ANN",o.stats.ann_profile||"exact"],["Nós no índice",(o.stats.ann_nodes||0).toLocaleString("pt-BR")],["Segmentos",o.stats.ann_segments||0],["Ef search",o.stats.ann_ef_search||"—"],["Cache",`${fmtBytes(o.stats.cache_bytes||0)} · ${o.stats.cache_items||0} itens`],["Disco",fmtBytes(o.stats.disk_file_bytes||0)]];$("#engine-stats").innerHTML=rows.map(([a,b])=>`<div class="stat-row"><span>${a}</span><strong>${b}</strong></div>`).join("")}
function startMonitor(){clearInterval(state.monitorTimer);state.monitorTimer=setInterval(async()=>{try{const overview=await api("/v1/admin/overview");renderOverview(overview);recordMonitorSample(overview)}catch(e){$("#monitor-last-sample").textContent="coleta interrompida"}},3000)}
function recordMonitorSample(o){const now=Date.now(),previous=state.monitor.at(-1),elapsed=previous?(now-previous.time)/1000:0,qps=previous&&elapsed>0?Math.max(0,((o.stats.search_requests_total||0)-previous.searches)/elapsed):0;state.monitor.push({time:now,qps,searches:o.stats.search_requests_total||0,heap:o.memory.heap_bytes||0,sys:o.memory.sys_bytes||0,pending:o.stats.replication_pending||0,committed:o.stats.replication_committed_offset||0,applied:o.stats.replication_applied_offset||0,overview:o});if(state.monitor.length>60)state.monitor.shift();if($("#page-monitor").classList.contains("active"))renderMonitor()}
function renderMonitor(){const sample=state.monitor.at(-1);if(!sample)return;const o=sample.overview,s=o.stats,cacheTotal=(s.cache_hits_total||0)+(s.cache_misses_total||0),cacheRate=cacheTotal?(s.cache_hits_total/cacheTotal)*100:null,annTotal=s.ann_searches_total||0,annFallback=annTotal?((s.ann_search_fallbacks_total||0)/annTotal)*100:null;$("#monitor-qps").textContent=sample.qps.toFixed(2);$("#monitor-cache-hit").textContent=cacheRate===null?"—":`${cacheRate.toFixed(1)}%`;$("#monitor-cache-volume").textContent=cacheTotal?`${cacheTotal.toLocaleString("pt-BR")} leituras observadas`:"sem leituras";$("#monitor-ann-fallback").textContent=annFallback===null?"—":`${annFallback.toFixed(1)}%`;$("#monitor-ann-volume").textContent=annTotal?`${annTotal.toLocaleString("pt-BR")} buscas ANN`:"sem buscas ANN";$("#monitor-replication-lag").textContent=sample.pending.toLocaleString("pt-BR");$("#monitor-last-sample").textContent=new Date(sample.time).toLocaleTimeString("pt-BR");$("#chart-qps-current").textContent=`${sample.qps.toFixed(2)} ops/s`;$("#chart-memory-current").textContent=`${fmtBytes(sample.heap)} heap`;$("#chart-replication-current").textContent=`${sample.pending} pendentes`;drawSeries($("#monitor-qps-chart"),[{values:state.monitor.map(x=>x.qps),color:"#8df7cf",fill:"#8df7cf18"}]);drawSeries($("#monitor-memory-chart"),[{values:state.monitor.map(x=>x.sys/1048576),color:"#68a9ff",fill:"#68a9ff12"},{values:state.monitor.map(x=>x.heap/1048576),color:"#8df7cf",fill:"#8df7cf12"}]);drawSeries($("#monitor-replication-chart"),[{values:state.monitor.map(x=>x.committed),color:"#f4d65e",fill:"#f4d65e10"},{values:state.monitor.map(x=>x.applied),color:"#8df7cf",fill:"#8df7cf10"}]);const rows=[["Vetores",o.vector_count.toLocaleString("pt-BR")],["Goroutines",o.goroutines],["Memória reservada",fmtBytes(o.memory.sys_bytes)],["Heap em uso",fmtBytes(o.memory.heap_bytes)],["Armazenamento",fmtBytes(s.disk_file_bytes||0)],["Falhas de replicação",(s.replication_failures_total||0).toLocaleString("pt-BR")]];$("#monitor-resources").innerHTML=rows.map(([a,b])=>`<div class="stat-row"><span>${a}</span><strong>${b}</strong></div>`).join("");const healthy=(s.replication_failures_total||0)===0&&sample.pending<100;$("#monitor-health-pill").textContent=healthy?"Saudável":"Atenção";$("#monitor-health-pill").classList.toggle("good",healthy)}
function drawSeries(canvas,series){const ratio=devicePixelRatio||1,rect=canvas.getBoundingClientRect();if(!rect.width)return;canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const c=canvas.getContext("2d");c.scale(ratio,ratio);const w=rect.width,h=rect.height,pad=18,all=series.flatMap(s=>s.values),max=Math.max(1,...all),min=Math.min(0,...all);c.strokeStyle="#24302e";c.lineWidth=1;for(let i=0;i<4;i++){const y=pad+i*(h-pad*2)/3;c.beginPath();c.moveTo(pad,y);c.lineTo(w-pad,y);c.stroke()}series.forEach(line=>{if(!line.values.length)return;const points=line.values.map((v,i)=>({x:pad+(i/Math.max(1,59))*(w-pad*2),y:h-pad-((v-min)/(max-min||1))*(h-pad*2)}));c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle=line.color;c.lineWidth=2;c.stroke();const last=points.at(-1);c.beginPath();c.arc(last.x,last.y,3,0,Math.PI*2);c.fillStyle=line.color;c.fill()})}
async function loadMap(limit,canvas){try{const data=await api(`/v1/admin/vectors/map?limit=${limit}`);state.map=data;drawMap(canvas,data);if(canvas.id==="vector-map")$("#map-meta").textContent=`${data.sampled} vetores · ${data.dimension} dimensões`}catch(e){toast(e.message,true)}}
function drawMap(canvas,data){const ratio=devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const c=canvas.getContext("2d");c.scale(ratio,ratio);c.clearRect(0,0,rect.width,rect.height);const pos=data.points.map((p,index)=>({x:24+p.x*(rect.width-48),y:24+(1-p.y)*(rect.height-48),id:p.id,index,values:p.values||[]}));c.strokeStyle="#304840";c.lineWidth=.7;data.edges.forEach(e=>{const a=pos[e.source],b=pos[e.target];if(!a||!b)return;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()});pos.forEach((p,i)=>{c.beginPath();c.arc(p.x,p.y,canvas.id==="vector-map"?4.2:2.4,0,Math.PI*2);c.fillStyle=i%7===0?"#e8fff6":"#78e9bd";c.fill()});const findHit=ev=>{const r=canvas.getBoundingClientRect(),x=ev.clientX-r.left,y=ev.clientY-r.top;let hit=null,d=144;pos.forEach(p=>{const n=(p.x-x)**2+(p.y-y)**2;if(n<d){d=n;hit=p}});return hit};canvas.onmousemove=ev=>{if(canvas.id!=="vector-map")return;const hit=findHit(ev);canvas.style.cursor=hit?"pointer":"crosshair";$("#vector-detail").textContent=hit?`vector: ${hit.id} · ${hit.values.length} dimensões · clique para abrir a matriz`:"Passe o cursor sobre um ponto para inspecionar o ID."};canvas.onclick=ev=>{if(canvas.id!=="vector-map")return;const hit=findHit(ev);if(hit)openVectorMatrix(hit)}}
function openVectorMatrix(point){$("#matrix-title").textContent=point.id;$("#matrix-meta").textContent=`1 × ${point.values.length} · valores float64 da representação original`;$("#matrix-grid").innerHTML=point.values.map((value,index)=>`<div class="matrix-cell"><small>[0, ${index}]</small><strong>${Number(value).toPrecision(7)}</strong></div>`).join("");$("#vector-matrix-dialog").showModal()}
$("#close-matrix").onclick=()=>$("#vector-matrix-dialog").close();
$("#vector-matrix-dialog").addEventListener("click",event=>{if(event.target===$("#vector-matrix-dialog"))$("#vector-matrix-dialog").close()});
const savedAPIKey=sessionStorage.getItem("lumenvec.admin.apiKey");
if(savedAPIKey){connect(savedAPIKey,{persist:false}).catch(error=>{sessionStorage.removeItem("lumenvec.admin.apiKey");state.key="";$("#app").classList.add("hidden");$("#auth").classList.remove("hidden");$("#login-error").textContent=`Sessão expirada: ${error.message}`})}
async function loadCluster(){try{const s=await api("/v1/admin/cluster");$("#provider").textContent=s.provider;$("#desired-nodes").textContent=s.desired_nodes;$("#add-node").disabled=!s.can_scale;$("#remove-node").disabled=!s.can_scale||s.desired_nodes<=1;$("#scale-hint").textContent=s.unavailable_reason||`Prontos: ${s.ready_nodes} de ${s.desired_nodes}`;$("#node-visual").innerHTML=Array.from({length:s.desired_nodes},(_,i)=>`<div class="node"><div><strong>${s.name||"lumenvec"}-${i}</strong><small>${i<s.ready_nodes?"ready":"provisionando"}</small></div></div>`).join("")}catch(e){toast(e.message,true)}}
async function scale(delta){if(!confirm(delta>0?"Adicionar um nó ao cluster?":"Remover um nó do cluster?"))return;try{const s=await api("/v1/admin/cluster/scale",{method:"POST",body:JSON.stringify({delta})});toast(`Escala desejada atualizada para ${s.desired_nodes}`);await loadCluster()}catch(e){toast(e.message,true)}}
$("#add-node").onclick=()=>scale(1);$("#remove-node").onclick=()=>scale(-1);
async function loadConfig(){try{const data=await api("/v1/admin/config");state.config=data.fields;renderConfig()}catch(e){$("#config-groups").innerHTML=`<p class="error">${e.message}</p>`}}
function renderConfig(){const groups=Object.groupBy?Object.groupBy(state.config,f=>f.category):state.config.reduce((a,f)=>((a[f.category]??=[]).push(f),a),{});$("#config-groups").innerHTML=Object.entries(groups).map(([name,fields])=>`<section class="config-group"><h4>${name}</h4><div class="field-grid">${fields.map(field=>`<div class="config-field"><label>${field.path}</label><input data-path="${field.path}" value="${String(field.value).replaceAll('"',"&quot;")}"><small>${field.restart_required?"requer reinício":"aplicação imediata"}</small></div>`).join("")}</div></section>`).join("");$$("[data-path]").forEach(input=>input.oninput=()=>{const original=state.config.find(f=>f.path===input.dataset.path).value;let value=input.value;if(typeof original==="boolean")value=value==="true";else if(typeof original==="number")value=Number(value);state.changes[input.dataset.path]=value;$("#save-config").disabled=false})}
$("#save-config").onclick=async()=>{try{const data=await api("/v1/admin/config",{method:"PATCH",body:JSON.stringify({changes:state.changes})});state.config=data.fields;state.changes={};renderConfig();$("#save-config").disabled=true;toast("Configuração salva. Reinício controlado necessário.")}catch(e){toast(e.message,true)}};
